# Generated by Django 5.2.13 on 2026-05-09 05:16

import apps.accounts.encryption
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_avatar_url_customuser_github_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google_vertex", "Google Vertex AI"),
                            ("mistral", "Mistral"),
                            ("custom", "Custom OpenAI-compatible"),
                        ],
                        max_length=30,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                (
                    "api_key",
                    apps.accounts.encryption.EncryptedCharField(max_length=500),
                ),
                ("base_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_userllmconfig",
                "ordering": ["priority", "-created_at"],
                "unique_together": {("user", "provider", "model_name")},
            },
        ),
    ]
