# Generated by Django 5.2.13 on 2026-04-25 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "github_id",
                    models.BigIntegerField(
                        help_text="GitHub's immutable numeric repository ID.",
                        unique=True,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        db_index=True,
                        help_text=(
                            "GitHub full name, e.g. 'acme/api'. May change on rename."
                        ),
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short repository name without owner prefix.",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_private", models.BooleanField(default=False)),
                ("default_branch", models.CharField(default="main", max_length=255)),
                ("html_url", models.URLField(max_length=500)),
                ("clone_url", models.URLField(max_length=500)),
                ("language", models.CharField(blank=True, default="", max_length=100)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("stargazers_count", models.PositiveIntegerField(default=0)),
                (
                    "webhook_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text=(
                            "GitHub webhook ID for this repo. Null if not installed."
                        ),
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text=(
                            "Kill switch: False disables all DevMind processing for"
                            " this repo."
                        ),
                    ),
                ),
                (
                    "review_enabled",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Whether AI code review is enabled for pull requests."
                        ),
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text=(
                            "When repository metadata was last synced from" " GitHub."
                        ),
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "repositories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "is_active"],
                        name="repositorie_owner_i_923519_idx",
                    ),
                    models.Index(
                        fields=["github_id"], name="repositorie_github__e97755_idx"
                    ),
                ],
            },
        ),
    ]
