# Generated by Django 5.2.13 on 2026-05-04 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("repositories", "0001_initial_repository_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepoScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("scanning", "Scanning"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Scan progress percentage 0-100."
                    ),
                ),
                (
                    "total_files",
                    models.IntegerField(
                        default=0, help_text="Total number of files to scan."
                    ),
                ),
                (
                    "files_scanned",
                    models.IntegerField(
                        default=0, help_text="Number of files scanned so far."
                    ),
                ),
                (
                    "total_issues",
                    models.IntegerField(default=0, help_text="Total issues found."),
                ),
                ("critical_count", models.IntegerField(default=0)),
                ("warning_count", models.IntegerField(default=0)),
                ("info_count", models.IntegerField(default=0)),
                ("scan_duration_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="repositories.repository",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repo_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reviews_reposcan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pr_number",
                    models.IntegerField(help_text="GitHub pull request number."),
                ),
                (
                    "pr_title",
                    models.CharField(
                        help_text="Pull request title from GitHub.", max_length=500
                    ),
                ),
                (
                    "head_sha",
                    models.CharField(
                        help_text="SHA of the head commit being reviewed.",
                        max_length=40,
                    ),
                ),
                (
                    "base_sha",
                    models.CharField(
                        help_text="SHA of the base commit.", max_length=40
                    ),
                ),
                (
                    "diff_url",
                    models.URLField(
                        help_text="URL to view the diff on GitHub.", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "risk_score",
                    models.IntegerField(
                        blank=True,
                        help_text="AI-calculated risk score from 0-100.",
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="AI-generated summary of the review.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="File path relative to repository root.",
                        max_length=500,
                    ),
                ),
                (
                    "line_number",
                    models.IntegerField(help_text="Line number in the diff."),
                ),
                ("body", models.TextField(help_text="Comment body/description.")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("quality", "Quality"),
                            ("tests", "Tests"),
                            ("style", "Style"),
                            ("performance", "Performance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "suggested_fix",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Suggested code fix in diff format.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_reviewcomment",
                "ordering": ["file_path", "line_number"],
            },
        ),
        migrations.CreateModel(
            name="ReviewRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_iterations",
                    models.IntegerField(
                        default=0, help_text="Number of agent retry iterations."
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        help_text="LLM model that generated the review (e.g. google/gemini-2.0-flash).",
                        max_length=100,
                    ),
                ),
                (
                    "prompt_tokens",
                    models.IntegerField(
                        default=0, help_text="Number of tokens in the prompt."
                    ),
                ),
                (
                    "completion_tokens",
                    models.IntegerField(
                        default=0, help_text="Number of tokens in the completion."
                    ),
                ),
                (
                    "latency_ms",
                    models.IntegerField(
                        default=0, help_text="LLM response time in milliseconds."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run",
                        to="reviews.review",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "review runs",
                "db_table": "reviews_reviewrun",
            },
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["repository", "pr_number"],
                name="reviews_rev_reposit_84d420_idx",
            ),
        ),
    ]
