# Generated by Django 5.2.13 on 2026-05-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reposcan",
            name="scan_id",
            field=models.IntegerField(
                blank=True, help_text="FastAPI scan ID", null=True
            ),
        ),
        migrations.AddField(
            model_name="reposcan",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
