# Generated by Django 5.2.13 on 2026-06-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0001_initial_repository_model"),
        ("reviews", "0002_reposcan_scan_id_reposcan_summary"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["completed_at"], name="reviews_rev_complet_e0457d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewcomment",
            index=models.Index(
                fields=["review", "severity"], name="reviews_rev_review__9fd57d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewcomment",
            index=models.Index(
                fields=["review", "file_path", "line_number"],
                name="reviews_rev_review__65e991_idx",
            ),
        ),
    ]
